silogica/core/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.classe, name='classe'),
    path('new/<str:classe>/', views.nclasse, name='nclasse'), 
    path('s/<str:classe>/', views.index, name='index'),
    path('silogismo/<int:key>/', views.exibir_silogismo, name='exibir_silogismo'),
    path('reducao/<int:key>/', views.reducao, name='reducao'),
    path('contato', views.contato, name='contato'),
    path('avalia', views.avalia, name='avalia'),
    path('e_erros', views.e_erro, name='e_erro'),
    path('erros/<str:classe>/', views.erros, name='erros'),
]

silogica/silogica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

silogica/core/models.py
from django.db import models
import uuid

class PREMISSAS(models.Model):
    classe = models.CharField(max_length=64, null=True)
    modo = models.CharField(max_length=40)
    reducao = models.CharField(max_length=40)
    extensao1 = models.CharField(max_length=20)
    termo1 = models.CharField(max_length=100)
    n1 = models.CharField(max_length=4)
    termo2 = models.CharField(max_length=100)
    extensao2 = models.CharField(max_length=20)
    termo3 = models.CharField(max_length=100)
    n2 = models.CharField(max_length=4)
    termo4 = models.CharField(max_length=100)
    extensao3 = models.CharField(max_length=20)
    termo5 = models.CharField(max_length=100)
    n3 = models.CharField(max_length=4)
    termo6 = models.CharField(max_length=100)
    
class REDUCAO(models.Model):
    sid_silogismo = models.IntegerField()
    sid_reducao = models.IntegerField()

class ERRO(models.Model):
    err_classe = models.CharField(max_length=64, null=True)
    err_sid = models.IntegerField()
    err_erro = models.CharField(max_length=50)

class CLASSE(models.Model):
    cla_codigo = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    cla_prof = models.CharField(max_length=100)

class E_CLASSE(models.Model):
    e_codigo = models.CharField(max_length=64)
    e_prof = models.CharField(max_length=100, null=True)

silogica/core/forms.py
from django import forms
from .models import PREMISSAS, CLASSE, E_CLASSE

class get_silogismo(forms.ModelForm):

    class Meta:
        model = PREMISSAS
        fields = ('extensao1','termo1','termo2','extensao2','termo3','termo4','extensao3','termo5','termo6')

class get_c_classe(forms.ModelForm):

    class Meta:
        model = CLASSE
        fields = ('cla_prof',)


class get_e_classe(forms.ModelForm):

    class Meta:
        model = E_CLASSE
        fields = ('e_codigo',)

class get_e_erro(forms.ModelForm):

    class Meta:
        model = E_CLASSE
        fields = ('e_codigo','e_prof',)

silogica/core/views.py
from django.shortcuts import render, redirect
from .forms import get_silogismo, get_c_classe, get_e_classe, get_e_erro
from .models import PREMISSAS, REDUCAO, ERRO, CLASSE
from . import models

#erros
e_termos1 = 'Encontrado erro referente aos termos, termo 1 igual ao termo 2'
e_termos2 = 'Encontrado erro referente aos termos, termo 3 igual ao termo 4'
e_termos3 = 'Encontrado erro referente aos termos, numero de termos diferente de 3'
e_negativas = 'Encontrado erro, de duas negativas nada se conclui'
e_particulares = 'Encontrado erro, de duas particulares nada se conclui'
e_conclusao = 'Encontrado erro referente a conclusão'
e_medio = 'Encontrado erro referente ao termo medio, termo medio não indentificado'
e_modos = 'Encontrado erro ao definir o modo do silogismo'

def bg1(s):
    s.termo1 = s.termo1.lower()
    s.termo2 = s.termo2.lower()
    s.termo3 = s.termo3.lower()
    s.termo4 = s.termo4.lower()
    s.termo5 = s.termo5.lower()
    s.termo6 = s.termo6.lower()

def s_erro(s, e):
    s.save()
    er= ERRO()
    er.err_classe = s.classe
    er.err_sid = s.id
    er.err_erro = e
    er.save()

def grava(x, r, s):
    s.modo = x
    s.reducao = r
    s.save()

def reducao_ok(r, s):
    r.save()
    print(r.id)
    red = REDUCAO()
    red.sid_silogismo = s.id
    red.sid_reducao = r.id
    red.save()

def reducao_error(r, s):
    r.save()
    red = REDUCAO()
    red.sid_silogismo = s.id
    red.sid_reducao = r.id
    red.save()

def classe(request):
    e_classe = get_e_classe(request.POST)
    c_classe = get_c_classe(request.POST)

    if e_classe.is_valid():
        cc = e_classe.save(commit=False)
        try:
            e = CLASSE.objects.get(cla_codigo=cc.e_codigo)
            classe = cc.e_codigo
            return redirect('/s/%s' % classe)
        except:
            erro = 'classe não existe'
            return render(request, 'ec_class.html', {'e_cla':e_classe, 'c_cla':c_classe, 'erro':erro})

    if c_classe.is_valid():
        cc = c_classe.save(commit=False)
        
        cc.save()
        classe = cc.cla_codigo
        return redirect('/new/%s' % classe)
    
    return render(request, 'ec_class.html', {'e_cla':e_classe, 'c_cla':c_classe})

def nclasse(request, classe):
    cod = classe
    return render(request, 'new_class.html', {'cod':cod})

def e_erro(request):
    e_erro = get_e_erro(request.POST)
    if e_erro.is_valid():
        cc = e_erro.save(commit=False)
        try:
            e = CLASSE.objects.get(cla_codigo=cc.e_codigo)
            if cc.e_prof == e.cla_prof:
                classe = cc.e_codigo
                return redirect('/erros/%s' % classe)
            else:
                erro = 'a classe informada não esta relacionada ao professor'
                return render(request, 'e_erro.html', {'e_erro':e_erro, 'erro':erro})               
        except:
            erro = 'classe não existe'
            return render(request, 'e_erro.html', {'e_erro':e_erro, 'erro':erro})


    return render(request, 'e_erro.html')

def index(request, classe):
    form = get_silogismo(request.POST)
    if form.is_valid():
        s = form.save(commit=False)
        s.classe = classe
        bg1(s)

        #auxiliares
        negativas = ['Nenhum', 'Algum não']
        particulares = ['Algum', 'Algum não']
        c_termos = [s.termo1, s.termo2, s.termo3, s.termo4]
        conclu = [s.termo5, s.termo6]

        #erro termos = na mesma premissa
        if s.termo1 == s.termo2:
            s_erro(s, e_termos1)
            return render(request, 'erro.html', {'erro': e_termos1})
        elif s.termo3 == s.termo4:
            s_erro(s, e_termos2)
            return render(request, 'erro.html', {'erro': e_termos2})

        #erro não tem 3 termos nas 2 premissas
        if c_termos.count(s.termo1) + c_termos.count(s.termo2) != 3:
            s_erro(s, e_termos3)
            return render(request, 'erro.html', {'erro': e_termos3})
        else:
            #erro duas negativas
            if negativas.count(s.extensao1) + negativas.count(s.extensao2) > 1:
                s_erro(s, e_negativas)
                return render(request, 'erro.html', {'erro': e_negativas})
            #erro duas particulares
            elif particulares.count(s.extensao1) + particulares.count(s.extensao2) > 1:
                s_erro(s, e_particulares)
                return render(request, 'erro.html', {'erro': e_particulares})
            else:
                # 1° figura
                if s.termo1 == s.termo4:
                    #erro conclusão
                    if s.termo2 != s.termo6 or s.termo3 != s.termo5:
                        s_erro(s, e_conclusao)
                        return render(request, 'erro.html', {'erro': e_conclusao})
                    else:
                        if s.extensao1 == 'Todo' and s.extensao2 == 'Todo' and s.extensao3 == 'Todo':
                            # BARBARA
                            x = 'Barbara'
                            r = 'Irredutivel'
                            grava(x, r, s)
                        elif s.extensao1 == 'Nenhum' and s.extensao2 == 'Todo' and s.extensao3 == 'Nenhum':
                            # CELARENT
                            x = 'Celarent'
                            r = 'Irredutivel'
                            grava(x, r, s)
                        elif s.extensao1 == 'Todo' and s.extensao2 == 'Algum' and s.extensao3 == 'Algum':
                            # DARII
                            x = 'Darii'
                            r = 'Irredutivel'
                            grava(x, r, s)
                        elif s.extensao1 == 'Nenhum' and s.extensao2 == 'Algum' and s.extensao3 == 'Algum não':
                            # FERIO
                            x = 'Ferio'
                            r = 'Irredutivel'
                            s.extensao3 = 'Algum'
                            s.n3 = 'não'
                            
                            grava(x, r, s)
                        #erro modo 1fig
                        else:
                            s_erro(s, e_modos)
                            return render(request, 'erro.html', {'erro': e_modos})


                elif s.termo2 == s.termo4:
                    # 2° figura
                    #erro conclusão
                    if s.termo1 != s.termo6 or s.termo3 != s.termo5:
                        s_erro(s, e_conclusao)
                        return render(request, 'erro.html', {'erro': e_conclusao})
                    else:
                        if s.extensao1 == 'Nenhum' and s.extensao2 == 'Todo' and s.extensao3 == 'Nenhum':
                            # CESARE
                            x = 'Cesare'
                            r = 'Celarent'
                            grava(x, r, s)
                        elif s.extensao1 == 'Todo' and s.extensao2 == 'Nenhum' and s.extensao3 == 'Nenhum':
                            # CAMESTRES
                            x = 'Camestres'
                            r = 'Celarent'
                            grava(x, r, s)
                        elif s.extensao1 == 'Nenhum' and s.extensao2 == 'Algum' and s.extensao3 == 'Algum não':
                            # FESTINO
                            x = 'Festino'
                            r = 'Ferio'
                            s.extensao3 = 'Algum'
                            s.n3 = 'não'
                            grava(x, r, s)
                        elif s.extensao1 == 'Todo' and s.extensao2 == 'Algum não' and s.extensao3 == 'Algum não':
                            # BAROCO
                            x = 'Baroco'
                            r = 'Irredutivel'
                            s.extensao3 = 'Algum'
                            s.n3 = 'não'
                            s.extensao2 = 'Algum'
                            s.n2 = 'não'
                            grava(x, r, s)
                        #erro modo 2fig
                        else:
                            s_erro(s, e_modos)
                            return render(request, 'erro.html', {'erro': e_modos})


                elif s.termo1 == s.termo3:
                    # 3° figura
                    #erro conclusão
                    if s.termo2 != s.termo6 or s.termo4 != s.termo5:
                        s_erro(s, e_conclusao)
                        return render(request, 'erro.html', {'erro': e_conclusao})
                    else:
                        if s.extensao1 == 'Todo' and s.extensao2 == 'Todo' and s.extensao3 == 'Algum':
                            # DARAPTI
                            x = 'Darapti'
                            r = 'Darii'
                            grava(x, r, s)
                        elif s.extensao1 == 'Nenhum' and s.extensao2 == 'Todo' and s.extensao3 == 'Algum não':
                            # FELAPTON
                            x = 'Felapton'
                            r = 'Ferio'
                            s.extensao3 = 'Algum'
                            s.n3 = 'não'
                            grava(x, r, s)
                        elif s.extensao1 == 'Nenhum' and s.extensao2 == 'Algum' and s.extensao3 == 'Algum não':
                            # FERISON
                            x = 'Ferison'
                            r = 'Ferio'
                            s.extensao3 = 'Algum'
                            s.n3 = 'não'
                            grava(x, r, s)
                        elif s.extensao1 == 'Algum' and s.extensao2 == 'Todo' and s.extensao3 == 'Algum':
                            # DISAMIS
                            x = 'Disamis'
                            r = 'Darii'
                            grava(x, r, s)
                        elif s.extensao1 == 'Algum não' and s.extensao2 == 'Todo' and s.extensao3 == 'Algum não':
                            # BOCARDO ajeitar
                            x = 'Bocardo'
                            r = 'Irredutivel'
                            s.extensao1 = 'Algum'

silogica/core/templates/avalia.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid my-3">
    <div class="row justify-content-md-center">
        <div class="col col-auto embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item"
                src="https://docs.google.com/forms/d/e/1FAIpQLScySaeYEL9GikQiBNAR7TTelZeGmn-RVQhSietZBlxX95KaQg/viewform?embedded=true"
                width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
        </div>
    </div>
    </section>
    {% endblock %}

silogica/core/templates/e_erro.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid col-7 mt-5">
    <div class=" justify-content-center ">
        <div class="card">
            <div class="alert alert-danger text-center">
                <h3>Entre na sua sala</h3>
                <span class="text-danger">{{erro}}</span>
            </div>
            <div class="card-body">
                <form method="POST" class="post-form">
                    <div class="input-group form-group justify-content-center row">
                        <input class="col-12 ml-4" placeholder="Codigo da sala" type="text" name="e_codigo"
                            maxlength="64" required id="id_e_codigo">
                        <input class="col-12 ml-4 my-3" placeholder="Nome do professor" type="text" name="e_prof"
                            maxlength="100" required id="id_e_prof">
                        <button type="submit" class="save btn btn-danger ml-2">Entrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

silogica/core/templates/reducao.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid my-3">
    <div class="card">
        <div class="card-header bg-danger text-white text-monospace">
            {{s.modo}}
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{s.extensao1}} {{s.termo1}} {{s.n1}} é {{ s.termo2}}<br />
                {{s.extensao2}} {{s.termo3}} {{s.n2}} é {{ s.termo4}}<br />
                {{s.extensao3}} {{s.termo5}} {{s.n3}} é {{ s.termo6}}</li>
            <li class="list-group-item bg-secondary text-white">reduz para {{s.reducao}}</li>
        </ul>
    </div>
    <section class="container-fluid" style="background-color: rgba(0, 0, 0, 0.5); color: white">
        <div class="p-2 my-2 ">
            <h4 class="mb-3 alert alert-danger text-center">Formulario para conferir a redução</h4>
            <form method="POST" class="post-form"><input type="hidden">
                <div class="d-flex flex-row-reverse">
                    <button id="modal-412867" href="#modal-container-412867" type="button"
                        class="btn btn-warning rounded-circle py-2 px-3" data-toggle="modal">?</button>
                </div>
                <div class="modal fade" id="modal-container-412867" role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document" style="color: rgb(20, 20, 20, 0.9)">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">
                                    Como usar o formulario
                                </h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                O usuario deve se atentar a alguns detalhes:<br />
                                - Não destiguimos se o caracter é maiusculo ou minusculo<br />
                                - Não indentificamos sinonimos<br />
                                - Palavras no plural tem são diferentes da mesma palavra no singular<br />

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>

                    </div>

                </div>
                <div class="mb-2 lead container-fluid" role="alert">
                    Premissa um
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao1">Extensão</label> <select class="form-control" name="extensao1"
                            id="id_extensao1">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo1">Termo um</label>
                        <input type="text" class="form-control" name="termo1" value="" maxlength="100" required
                            id="id_termo1">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo2">Termo dois:</label>
                        <input type="text" class="form-control" name="termo2" value="" maxlength="100" required
                            id="id_termo2">
                    </div>
                </div>
                <div class="lead container-fluid" role="alert">
                    Premissa dois
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao2">Extensão</label> <select class="form-control" name="extensao2"
                            id="id_extensao2">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo3">Termo três</label>
                        <input class="form-control" type="text" name="termo3" value="" maxlength="100" required
                            id="id_termo3">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo4">Termo quatro</label>
                        <input class="form-control" type="text" name="termo4" value="" maxlength="100" required
                            id="id_termo4">
                    </div>
                </div>
                <div class="mb-2 lead container-fluid" role="alert">
                    Conclusão
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao3"></label> <select class="form-control" name="extensao3"
                            id="id_extensao3">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo5"></label>
                        <input class="form-control" type="text" name="termo5" value="" maxlength="100" required
                            id="id_termo5">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo6"></label>
                        <input class="form-control" type="text" name="termo6" value="" maxlength="100" required
                            id="id_termo6">
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="save container btn btn-danger justify-content-md-center">Conferir
                        silogismo</button>
                </div>
            </form>
        </div>
    </section>
    {% endblock %}

silogica/core/templates/reducao_error.html
{% extends 'base.html' %} {% block content %}

<div id="exemplomodal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Erro na reducao</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" id="modal-41286" href="#modal-container-41286" type="button" class="btn btn-warning"
                    data-toggle="modal">Ver redução correta para {{s.reducao}}</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<!-- bootstrap -->
<script type="text/javascript" src="js/bootstrap.js"></script>
<!-- chamada da função -->
<script type="text/javascript">
    $(window).load(function () {
        $('#exemplomodal').modal('show');
    });
</script>

<div class="container-fluid my-3">
    <div class="card">
        <div class="card-header bg-danger text-white text-monospace">
            {{s.modo}}
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{s.extensao1}} {{s.termo1}} {{s.n1}} é {{ s.termo2}}<br />
                {{s.extensao2}} {{s.termo3}} {{s.n2}} é {{ s.termo4}}<br />
                {{s.extensao3}} {{s.termo5}} {{s.n3}} é {{ s.termo6}}</li>
            <li class="list-group-item bg-secondary text-white">reduz para {{s.reducao}}
            </li>
        </ul>
    </div>
    <section class="container-fluid" style="background-color: rgba(0, 0, 0, 0.5); color: white">
        <div class="p-2 my-2 ">
            <h4 class="mb-3 alert alert-danger text-center">Formulario para conferir a redução</h4>
            <form method="POST" class="post-form"><input type="hidden">
                <div class="d-flex flex-row-reverse">
                    <button id="modal-412867" href="#modal-container-412867" type="button"
                        class="btn btn-warning rounded-circle py-2 px-3" data-toggle="modal">?</button>
                </div>
                <div class="modal fade" id="modal-container-412867" role="dialog" aria-labelledby="myModalLabel" style="color: rgb(20, 20, 20, 0.9)"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">
                                    Como usar o formulario
                                </h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                O usuario deve se atentar a alguns detalhes:<br />
                                - Não destiguimos se o caracter é maiusculo ou minusculo<br />
                                - Não indentificamos sinonimos<br />
                                - Palavras no plural tem são diferentes da mesma palavra no singular<br />

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>

                    </div>

                </div>
                <div class="mb-2 lead container-fluid" role="alert">
                    Premissa um
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao1">Extensão</label> <select class="form-control" name="extensao1"
                            id="id_extensao1">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo1">Termo um</label>
                        <input type="text" class="form-control" name="termo1" value="" maxlength="100" required
                            id="id_termo1">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo2">Termo dois:</label>
                        <input type="text" class="form-control" name="termo2" value="" maxlength="100" required
                            id="id_termo2">
                    </div>
                </div>
                <div class="lead container-fluid" role="alert">
                    Premissa dois
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao2">Extensão</label> <select class="form-control" name="extensao2"
                            id="id_extensao2">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo3">Termo três</label>
                        <input class="form-control" type="text" name="termo3" value="" maxlength="100" required
                            id="id_termo3">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo4">Termo quatro</label>
                        <input class="form-control" type="text" name="termo4" value="" maxlength="100" required
                            id="id_termo4">
                    </div>
                </div>
                <div class="mb-2 lead container-fluid" role="alert">
                    Conclusão
                </div>
                <div class="row">
                    <div class="col-md-2 mb-3">
                        <label for="id_extensao3"></label> <select class="form-control" name="extensao3"
                            id="id_extensao3">
                            <option value="Todo" selected>Todo</option>

                            <option value="Algum">Algum</option>

                            <option value="Nenhum">Nenhum</option>

                            <option value="Algum não">Algum não</option>
                        </select>
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo5"></label>
                        <input class="form-control" type="text" name="termo5" value="" maxlength="100" required
                            id="id_termo5">
                    </div>
                    <div class="col-md-5 mb-4">
                        <label for="id_termo6"></label>
                        <input class="form-control" type="text" name="termo6" value="" maxlength="100" required
                            id="id_termo6">
                    </div>
                </div>
                <div class="row">
                    <button type="submit" class="save container btn btn-danger justify-content-md-center">Conferir
                        silogismo</button>
                </div>
            </form>
        </div>

        <div style="color: rgb(20, 20, 20, 0.9)" class="modal fade" id="modal-container-41286" role="dialog" aria-labelledby="myModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="container-fluid my-3">
                        <div class="card">
                            <div class="card-header bg-danger text-white text-monospace">
                                {{s.reducao}}
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">{{r.extensao1}} {{r.termo1}} {{r.n1}} é {{ r.termo2}}<br />
                                    {{r.extensao2}} {{r.termo3}} {{r.n2}} é {{ r.termo4}}<br />
                                    {{r.extensao3}} {{r.termo5}} {{r.n3}} é {{ r.termo6}}</li>
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>


    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% endblock %}